/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:bf74acc1-dc15-4738-b18f-9613b86edb2b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Bi4zRafmI",
    "aws_user_pools_web_client_id": "6njl5png7ogjr2fukksirefie9",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "ee-aws-bucket173627-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "allevents",
            "endpoint": "https://20b7qq95v6.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        },
        {
            "name": "Impressions",
            "endpoint": "https://4eoh1izh32.execute-api.us-east-1.amazonaws.com/beta",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
